### ISSUE TITLE
null checks on public apis?

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#317]
I created a go program based on https://github.com/breez/breez-sdk-go. Called `connect` with a nil EventListener, like this:
```
breezServices, err := breez_sdk.Connect(config, seed, nil)
```

That then failed with this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1000a3b0d]

goroutine 17 [running, locked to thread]:
github.com/breez/breez-sdk-go/breez_sdk.foreignCallbackTypeEventListener.InvokeOnEvent({}, {0x0, 0x0}, {0x8, 0x4, 0x129606b00, {0x8, 0x4, 0x129606b00}})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:4426 +0x16d
github.com/breez/breez-sdk-go/breez_sdk.breez_sdk_b490_cgo_EventListener(0xc000062e28?, 0x1, {0x7c000?, 0xc0?, 0x129606b00?}, 0x70000c3c1620)
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:4410 +0xea
```

I'd expect if an argument cannot be nil/null, you'd get an error straight away, saying: 'this parameter cannot be null'.
I think this goes for all apis.

**Comment by JssDWt** [comment]
Similarly, there is a scary error from setting an empty invite code (not nil, empty) in the config:
```
inviteCode := ""
config := breez_sdk.DefaultConfig(breez_sdk.EnvironmentTypeProduction, apikey, breez_sdk.NodeConfigGreenlight{
  Config: breez_sdk.GreenlightNodeConfig{
	  InviteCode: &inviteCode,
  },
})
```

Error:

```
panic: EOF

goroutine 1 [running]:
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterstring.read({}, {0x1000f0d98, 0xc00011c2a0})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:817 +0x117
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterOptionalstring.read({}, {0x1000f0d98, 0xc00011c2a0})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:4680 +0x49
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterTypeGreenlightNodeConfig.read({}, {0x1000f0d98, 0xc00011c2a0})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:1875 +0x39
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterTypeNodeConfig.read({}, {0x1000f0d98, 0xc00011c2a0})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:3935 +0x3b
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterTypeConfig.read({}, {0x1000f0d98, 0xc00011c2a0})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:1684 +0x13a
github.com/breez/breez-sdk-go/breez_sdk.liftFromRustBuffer[...]({0x1000f1058?, 0x1001ae480}, {0x120, 0xb6, 0x129904100, {0x120, 0xb6, 0x129904100}})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:415 +0x1b6
github.com/breez/breez-sdk-go/breez_sdk.FfiConverterTypeConfig.lift({}, {0x8?, 0x0?, 0x129904100?})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:1671 +0x125
github.com/breez/breez-sdk-go/breez_sdk.DefaultConfig(0xc00010c168?, {0x1000d5e4a?, 0x1?}, {0x1000f1118?, 0xc00011a290?})
        /Users/jessedewit/go/pkg/mod/github.com/breez/breez-sdk-go@v0.0.0-20230711093707-0ff5e7035da3/breez_sdk/breez_sdk.go:5702 +0xd5
main.main()
        /Users/jessedewit/Projects/breez/test-breez-sdk-go/main.go:20 +0x85
```

**Comment by roeierez** [comment]
The invite code issues seems like a uniffi convertor bug.

**Comment by roeierez** [comment]
Both issues seems due to uni-ffi conversion code. In rust we get Box<EventListener> which can't be null but the binding creates an interface for that which allows languages like golang pass nil.
I think that to fix this issue we need to define the passed argument as Optional<Box<EventListener>> and then we can test for existence in rust.

**Comment by JssDWt** [comment]
This is fixed, because the connect api has changed, and optional values are now actually optional since https://github.com/breez/breez-sdk/pull/416
