### ISSUE TITLE
Failed to load dynamic library 'libbreez_sdk_core.so'

### ISSUE THREAD

**Issue by aniketambore** [breez/breez-sdk#321]
I encountered an error while testing the [Breez SDK Flutter](https://github.com/breez/breez-sdk/tree/main/libs/sdk-flutter) plugin on Android. The error message states the following:
`Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_core.so': dlopen failed: library "libbreez_sdk_core.so" not found`

Complete Error:
```shell
════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building Builder:
Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_core.so': dlopen failed: library "libbreez_sdk_core.so" not found

The relevant error-causing widget was
MaterialApp
main.dart:87
When the exception was thrown, this was the stack
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      getNativeToolkit
native_toolkit.dart:17
#3      new BreezBridge
breez_bridge.dart:10
#4      breezBridge
main.dart:13
#5      breezBridge (package:breez_sdk_demo_app/main.dart)
main.dart:1
#6      _HomeScreenState.initState
main.dart:105
#7      StatefulElement._firstBuild
framework.dart:5219
#8      ComponentElement.mount
framework.dart:5062
...     Normal element mounting (220 frames)
#228    Element.inflateWidget
framework.dart:3971
#229    MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#230    MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (467 frames)
#697    Element.inflateWidget
framework.dart:3971
#698    Element.updateChild
framework.dart:3708
#699    RenderObjectToWidgetElement._rebuild
binding.dart:1240
#700    RenderObjectToWidgetElement.mount
binding.dart:1209
#701    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
binding.dart:1156
#702    BuildOwner.buildScope
framework.dart:2720
#703    RenderObjectToWidgetAdapter.attachToRenderTree
binding.dart:1155
#704    WidgetsBinding.attachRootWidget
binding.dart:988
#705    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
binding.dart:968
#709    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
```
Here are the details of my environment:
- Flutter SDK version: 3.10.5
- Dart: 3.0.5
- Flutter doctor output:

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-IN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources
```

I am testing the SDK on the Android Emulator with the following configuration:
- Device: Nexus 5X
- Release Name: S
- API Level: 31
- ABI: x86_64
- Target Android: 12.0

I would appreciate any guidance or suggestions on resolving this issue. Thank you!

**Comment by roeierez** [comment]
Hi, thanks for reporting.
Did you run "make android"?
Can you make sure the native ibraries were built under the android/src/main/jniLibs/ directory?

**Comment by aniketambore** [comment]
Thank you for your response. Yes, I've been running the "make android" command to build the native libraries for the Android platform. However, I'm encountering some errors during the build process, specifically related to the openssl-sys component. These errors are preventing the successful creation of the libraries under the android/src/main/jniLibs/ directory.

Trying different solutions to resolve them. I will keep you updated on my progress and provide further details once I have successfully resolved the errors and built the native libraries.

**Comment by dangeross** [comment]
Hi, can you comment with the errors you are getting? It could be on Windows that you need to statically link OpenSSL or make sure a compatible perl is being used.

**Comment by aniketambore** [comment]
Hi @dangeross , From now onwards, it's a bit of off time for me as it's nighttime here. Tomorrow, I'll provide you with the specific error messages. However, regarding the points you mentioned, I am indeed encountering errors related to OpenSSL and Perl. I attempted to install Strawberry Perl and also performed some OpenSSL installations, but the errors persist. 

I'll make sure to include all those error messages tomorrow when I provide an update. Thanks!

**Comment by aniketambore** [comment]
Hi, I encountered the error while running the `make android` command. Here are the details of the error:

```shell
error: failed to run custom build command for `openssl-sys v0.9.88`

Caused by:
  process didn't exit successfully: `D:\Flutter My Local Projects\breez-sdk\libs\target\release\build\openssl-sys-fd7b0b6f2ce6e81a\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=CC_armv7-linux-androideabi        
  CC_armv7-linux-androideabi = Some("C:\\Users\\anike\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang")
  cargo:rerun-if-env-changed=CFLAGS_armv7-linux-androideabi    
  CFLAGS_armv7-linux-androideabi = None
  cargo:rerun-if-env-changed=CFLAGS_armv7_linux_androideabi    
  CFLAGS_armv7_linux_androideabi = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=AR_armv7-linux-androideabi        
  AR_armv7-linux-androideabi = Some("C:\\Users\\anike\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar")
  cargo:rerun-if-env-changed=ARFLAGS_armv7-linux-androideabi   
  ARFLAGS_armv7-linux-androideabi = None
  cargo:rerun-if-env-changed=ARFLAGS_armv7_linux_androideabi   
  ARFLAGS_armv7_linux_androideabi = None
  cargo:rerun-if-env-changed=TARGET_ARFLAGS
  TARGET_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=RANLIB_armv7-linux-androideabi    
  RANLIB_armv7-linux-androideabi = Some("C:\\Users\\anike\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ranlib")
  cargo:rerun-if-env-changed=RANLIBFLAGS_armv7-linux-androideabi
  RANLIBFLAGS_armv7-linux-androideabi = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_armv7_linux_androideabi
  RANLIBFLAGS_armv7_linux_androideabi = None
  cargo:rerun-if-env-changed=TARGET_RANLIBFLAGS
  TARGET_RANLIBFLAGS = None
  cargo:rerun-if-env-changed=RANLIBFLAGS
  RANLIBFLAGS = None
  running "perl" "./Configure" "--prefix=D:\\Flutter My Local Projects\\breez-sdk\\libs\\target\\armv7-linux-androideabi\\release\\build\\openssl-sys-9e570dd703bcc9b9\\out\\openssl-build\\install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=armv7-linux-androideabi"
  Configuring OpenSSL version 1.1.1u (0x1010115fL) for linux-armv4
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  --- stderr
  Can't locate Pod/Usage.pm in @INC (you may need to install the Pod::Usage module) (@INC contains: . /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at configdata.pm line 10068.
  BEGIN failed--compilation aborted at configdata.pm line 10068.
  Compilation failed in require.
  BEGIN failed--compilation aborted.
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=D:\\Flutter My Local Projects\\breez-sdk\\libs\\target\\armv7-linux-androideabi\\release\\build\\openssl-sys-9e570dd703bcc9b9\\out\\openssl-build\\install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=armv7-linux-androideabi"
      Exit status: exit code: 1
```

**Comment by aniketambore** [comment]
To provide additional context regarding my previous comment, I'm trying to execute the build command mentioned in [here](https://github.com/breez/breez-sdk/tree/main/libs/sdk-flutter) using the Git Bash terminal on my Windows machine. The reason for using the Git Bash terminal is that I have previously utilized it to run makefile commands.

**Comment by JssDWt** [comment]
@aniketambore Here's a stackoverflow post that describes the possible steps to take: https://stackoverflow.com/a/68769192/3883866

In particular I think it should work when you've installed strawberry perl. Make sure it's high up in your PATH, so the build doesn't accidentally default to msys perl.

**Comment by aniketambore** [comment]
Hi @JssDWt, thank you for providing the information and the link to the StackOverflow post. I want to let you know that the plugin is now available directly on GitHub here: https://github.com/breez/breez-sdk-flutter, so there is no longer a need to build the native libraries manually. I'm simply referring to it in the `pubspec.yaml` file to use it.

**Comment by JssDWt** [comment]
@aniketambore Great that that's working for you. I'll close this issue then. Feel free to reopen if necessary.
