### ISSUE TITLE
Failed to load libbreez_sdk_bindings.so

### ISSUE THREAD

**Issue by ademar111190** [breez/breez-sdk#490]
I just build the breez sdk at main branch (commit 508e436) and c-breez app at main branch (commit [eee834d](https://github.com/breez/c-breez/commit/eee834df2b565a836f4cd4f3d040771de9a562d8)) and I got the following error when opening the app:

arm64 device:
```
2023-09-28T09:16:05.402362	E	Main:	 FlutterError: Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_bindings.so': dlopen failed: library "libbreez_sdk_bindings.so" not found
Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_bindings.so': dlopen failed: library "libbreez_sdk_bindings.so" not found
	#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
	#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
	#2      getNativeToolkit (package:breez_sdk/native_toolkit.dart:17:51)
	#3      new BreezSDK (package:breez_sdk/breez_bridge.dart:10:22)
	#4      ServiceInjector.breezSDK (package:c_breez/services/injector.dart:53:42)
	#5      main.<anonymous closure> (package:c_breez/main.dart:53:31)
	<asynchronous suspension>
```

x86_64 emulator:
```
2023-09-28T09:17:18.578389	E	Main:	 FlutterError: Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_bindings.so': dlopen failed: library "libbreez_sdk_bindings.so" not found
Invalid argument(s): Failed to load dynamic library 'libbreez_sdk_bindings.so': dlopen failed: library "libbreez_sdk_bindings.so" not found
	#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
	#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
	#2      getNativeToolkit (package:breez_sdk/native_toolkit.dart:17:51)
	#3      new BreezSDK (package:breez_sdk/breez_bridge.dart:10:22)
	#4      ServiceInjector.breezSDK (package:c_breez/services/injector.dart:53:42)
	#5      main.<anonymous closure> (package:c_breez/main.dart:53:31)
	<asynchronous suspension>
```

**Comment by JssDWt** [comment]
@ademar111190 Can you try this version of the flutter release?
https://github.com/breez/breez-sdk/suites/16656266724/artifacts/951704308

**Comment by ademar111190** [comment]
It is working, thanks @JssDWt :pray:

**Comment by JssDWt** [comment]
The problem was a custom build script. That broke because of these reckless changes.
